# Generated by Django 5.2.1 on 2025-05-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_page_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.CharField(max_length=255),
        ),
    ]
