# Generated by Django 5.2.1 on 2025-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('loan_time', models.DateField()),
                ('loan_period', models.IntegerField()),
            ],
        ),
    ]
