# Generated by Django 5.2.1 on 2025-05-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'User'), (2, 'Guest')], default=2),
        ),
    ]
